[tool.poetry]
name = "davidkhala.azure"
version = "0.0.0"
description = "@davidkhala/azure-utils"
authors = ["David Liu <david-khala@hotmail.com>"]
readme = "README.md"
packages = [{ include = "auth" }]

[tool.poetry.dependencies]
azure-identity = ">=1"
requests = ">=2"

[tool.poetry.group.dev.dependencies]
pytest=">=8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"